export const GET_USERS = "GET_USERS";
export const GET_USERS_REQUESTED = "GET_USERS_REQUESTED";
export const SHOW_POPUP = "SHOW_POPUP";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
export const SET_TOTAL_PAGES = "SET_TOTAL_PAGES";
